<a href="https://colab.research.google.com/github/nhemanth1103/Tensorflow_Learnings/blob/main/tensorflowDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

1.create a tensor 2*3 floating point number values
[[1.2, 3.4, 5.6], [7.8, 9.0, 1.1]]

In [ ]:
import tensorflow as tf
#creating a tensor
tensor_1=tf.constant([[1.2, 3.4, 5.6], [7.8, 9.0, 1.1]],dtype=tf.float32)
#print the tensor shape and it's type
print("Tensor:\n",tensor_1)
print("Tensor shape:",tensor_1.shape)
print("Tensor type:",tensor_1.dtype)

Tensor:
 tf.Tensor(
[[1.2 3.4 5.6]
 [7.8 9.  1.1]], shape=(2, 3), dtype=float32)
Tensor shape: (2, 3)
Tensor type: <dtype: 'float32'>


Problem 2: Tensor Operations
Create two 3x3 tensors and perform element-wise addition, subtraction, and multiplication.[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [ ]:
import tensorflow as tf
tensor_1=tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]],dtype=tf.int32)
tensor_2=tf.constant([[9, 8, 7], [6, 5, 4], [3, 2, 1]],dtype=tf.int32)
add_tensors=tf.add(tensor_1,tensor_2)
sub_tensor=tf.subtract(tensor_1,tensor_2)
div_tensor=tf.divide(tensor_1,tensor_2)
multiply_tensor=tf.multiply(tensor_1,tensor_2)
print("Additional results:\n",add_tensors)
print("substraction result:\n",sub_tensor)
print("division results\n",div_tensor)
print("multiply results\n",multiply_tensor)

Additional results:
 tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int32)
substraction result:
 tf.Tensor(
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]], shape=(3, 3), dtype=int32)
division results
 tf.Tensor(
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]], shape=(3, 3), dtype=float64)
multiply results
 tf.Tensor(
[[ 9 16 21]
 [24 25 24]
 [21 16  9]], shape=(3, 3), dtype=int32)


Problem 3: Reshaping a Tensor
Create a tensor of shape (3, 2) and reshape it into a tensor of shape (2, 3).values[[1, 2], [3, 4], [5, 6]]


In [ ]:
import tensorflow as tf
tensor_a=tf.constant([[1, 2], [3, 4], [5, 6]],dtype=tf.int32)
tensor_b=tf.reshape(tensor_a,[2,3])
print(tensor_b)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Problem 4: Creating Zeros and Ones Tensors
Create a tensor of all zeros of shape (3, 3) and another tensor of all ones of shape (2, 4).

In [ ]:
import tensorflow as tf
tensor_zeros=tf.zeros([3,3])
tensor_ones=tf.ones({2,4})
print("zeros tensor:\n",tensor_zeros)
print("ones tensor:\n",tensor_ones)

zeros tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
ones tensor:
 tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


Problem 5: Random Tensors
Generate a 4x4 tensor with random values from a normal distribution and a 2x2 tensor with random values from a uniform distribution.....?UNIFORM:Values are equally likely within a given range(minval,maxval).
NORMAL:Values cluster around the mean, following a bell curve(mean,stddev).

In [ ]:
import tensorflow as tf
normal_tensor=tf.random.normal([4,4],mean=0,stddev=1)
uniform_tensor=tf.random.uniform([2,2],minval=0,maxval=1)
print("Normal distrubution tensor:\n",normal_tensor)
print("Uniform distrubution tensor:\n",uniform_tensor)

Normal distrubution tensor:
 tf.Tensor(
[[-1.0432969   0.90708536  0.7989642  -1.0304294 ]
 [-0.08852495 -0.21376167 -0.25020835 -0.57017976]
 [ 0.48617557  1.3563063  -0.8597052  -0.7922548 ]
 [ 1.2525339  -0.39352372 -0.4467469  -0.4530071 ]], shape=(4, 4), dtype=float32)
Uniform distrubution tensor:
 tf.Tensor(
[[0.69784975 0.5108408 ]
 [0.14973617 0.84783447]], shape=(2, 2), dtype=float32)
